---
output:
  pdf_document:
    citation_package: natbib
    fig_caption: yes
    template: ./resources/aog-latex-ms.tex
  word_document:
    reference_docx: ./resources/aog_word_style.docx
fontfamily: mathpazo
fontsize: 11pt
anonymous: false
endnotes: false
pagenumber: 1
bibliography: ../project.bib
biblio-style: ./resources/ajs.bst
title: "Fertility Effects of a Belief in Climate Change"
author:Isabella Clark
- affiliation: University of Oregon, Sociology
  name: 
keywords: climate change, fertility rates, family planning, environmental sociology
thanks: Thanks to Aaron Gulllickson for all the R assists. 
abstract: This is a test abstract
---

# Introduction
My paper seeks to understand if there is an emergent trend in increasing concerns about climate change and declining fertility rates. Specifically, I am interested in the possible intersection between the well-documented lowering of birth rates in affluent nations and the growing awareness and concern over anthropogenic climate change. For this study, I will focus on the United States, an affluent country in which there has been political denialism around climate change, although a large majority of Americans now believe climate change is happening (Leiserowitz et al 2018). This project analyzes whether American women who do believe in anthropogenic climate change are reducing the number of children they have in response. I will contrast their feritlity rates with those of American women who show no belief in or concern about climate change. 


# Data and Methods
The dataset I used in this project is the ANES 2016 Time Series Study. ANES is the most suitable dataset I have found at this time to answer this research question. I wanted data that dealt both with the question of anthropogenically caused climate change and included respondents' demographic information. Since this 2016 ANES Time Series Study includes questions on cliamte change belief and demographics, it was an appropriate choice for this research question. I also needed information on fertility rates. The ANES 2016 Time Series Study included a question on whether respondents had children under 18 living in their households. Although this is an imperfect metric, no other dataset contained variables on respondents' climate change beliefs, demographics, and fertility rates.

The ANES 2016 Time Series Study was conducted in two waves, pre-and post-election. Both web interviews and face-to-face interviews were used to gather data. The ANES website states, "The data can be analyzed using the combined dual-mode sample, or using the face-to-face sample alone, or using the Internet sample alone." I subset the data for the face-to-face sample and only analyzed this sample as it included unique information on respondents' household demographics regarding children. Variables on climate change belief came only from the pre-election wave of interviews. 

As control variables, I planned to use age and gender. Age as a variable is problematic in this dataset. First, the categories for age are very large, under 18, 18-39, 40-59 and 60+, making it difficult to look at variation between age categories and climate beliefs and fertility. Additionally, many respondents chose not to answer, resulting in a great deal of missing variables which shrunk my dataset in analysis between models. 

Additionally, I had initially planned to focuse on class as a control variable and that directly relates to literature on family planning. I was going to use education as well as income as rough measures of SES. The limitation here is that income is a restricted variable in the dataset. Though a few respondents chose to include this data publicly, it was too small of a number to be statistically significant. Education was also a problem. Interviewers asked respondents to choose from three categories: less than high school, high school, and more than high school. Obviously the category "more than high school" contains a great deal of hidden information. Someone who has completed some community college classes has indeed obtained "more than a high school" education, yet would not likely be at the same SES as someone who completed either a bachelors degree or a graduate level education. Clearly, this dataset has proved to contain many limitations for adequately studying demographics of respondents which may effect both their climate change beliefs and their choices to have children. To look at the climate change variable further, I also included information about whether climate change was seen as anthropogenically caused, the result of natural processes, or equally caused by each. 

# Results
An encouraging result from my project is that most resondents overall do believe in climate change. However, a greater proportion of respondents think climate change is equally due to human and natural causes, rather than being all anthropogenically caused. This is troublesome because it may encourage respondents to defer responsibility from both themselves and the government to address climate change. 

# Conclusions

# References
Leiserowitz, A., Maibach, E., Roser-Renouf, C., Rosenthal, S., Cutler, M., & Kotcher, J. (2018). Climate change in the American mind: March 2018. Yale University and George Mason University. New Haven, CT: Yale Program on Climate Change Communication.